name: Deploy Sanity Studio
on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/studio/**'
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
      SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
      SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
      SANITY_STUDIO_TITLE: ${{ secrets.SANITY_STUDIO_TITLE }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - uses: oven-sh/setup-bun@v2
      - name: Deploy Sanity Studio
        run: |
          cd ./apps/studio
          bun install
          bun run sanity deploy
